image: python:3.8-slim

stages:
  - documentation

pages:
  tags:
    - shared_docker
  stage: documentation
  before_script:
    - pip install -r requirements.txt
    - chmod +x ./.github/scripts/clone.sh
    - ./.github/scripts/clone.sh https://github.com/ifm/documentation main sphinx-doc/source/documentation
    - ./.github/scripts/clone.sh https://github.com/ifm/ifm3d-ros.git master sphinx-doc/source/ROS/ifm3d-ros  
    - ./.github/scripts/clone.sh https://github.com/ifm/ifm3d-ros2.git master sphinx-doc/source/ROS/ifm3d-ros2      
  script:
    - rm -rf docs
    - sphinx-build source docs
    - sphinx-build -b linkcheck source docs
    - mv docs public
  artifacts:
    paths:
      - public

