
name: Build docs
on:
  push:
  schedule:
    - cron:  '*/15 * * * *'
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }} 

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses:  actions/setup-python@v2
      with:
        python-version: '3.9'
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
        submodules: true
    # Update references
    - name: Git Submodule Update
      run: |
        rm -rf sphinx-doc/source/ifm3d sphinx-doc/source/documentation sphinx-doc/etc/ifm3d-docs
        git submodule update --init --recursive
    - name: Install reqs
      run: |
        pip install -r sphinx-doc/requirements.txt
    - name: Build docs
      run: |
        cd sphinx-doc 
        rm -r -f build
        cp source/ifm3d/README.md source/ifm3d/doc/sphinx/content
        make html
        cp -r etc/ifm3d-docs/cpp_api build/html/ifm3d/doc/sphinx/
    - name: Push built docs
      run: |
        git config --global user.email "support.robotics@ifm.com"
        git config --global user.name "ifm-csr"
        git checkout -B pipeline
        git add build
        git commit -m "Updated built docs"
        git push --set-upstream origin pipeline
      # - git clone -b gh_pages https://${DEVELOPERPORTAL}:x-oauth-basic@github.com/ifm/developerportal.git repo
      # - cd repo
      # - mkdir ./public
      # - cp -r ${CI_PROJECT_DIR}/public/* ./public
      # - git add -A
      # - git commit -m "build sphinx docs" --allow-empty
      # - git push
