
name: Build docs
on:
  push:
    branches:
    - '**'        # matches every branch
    - '!pipeline'
  schedule:
    - cron:  '*/15 * * * *'
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }} 

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses:  actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: GH_TOKEN
      if: env.GH_TOKEN == ''
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: echo "GH_TOKEN=${GITHUB_TOKEN}" >> $GITHUB_ENV        
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
        submodules: true
    # Update references
    - name: Git Repos Update
      run: | 
        chmod +x ./.github/scripts/clone.sh
        ./.github/scripts/clone.sh https://github.com/ifm/ifm3d o3r/main-next sphinx-doc/source/ifm3d
        ./.github/scripts/clone.sh https://github.com/ifm/documentation sphinx_update sphinx-doc/source/documentation
        ./.github/scripts/clone.sh https://github.com/ifm/ifm3d-docs main sphinx-doc/etc/ifm3d-docs               
    - name: Install reqs
      run: |
        pip install -r sphinx-doc/requirements.txt
    - name: Build docs
      run: |
        cd sphinx-doc 
        rm -r -f build
        cp source/ifm3d/README.md source/ifm3d/doc/sphinx/content
        make html
        cp -r etc/ifm3d-docs/cpp_api build/html/ifm3d/doc/sphinx/
    - name: Push built docs
      run: |
        git config --global user.email "support.robotics@ifm.com"
        git config --global user.name "ifm-csr"
        git checkout -B pipeline
        git merge origin/lm_global_doc_pipeline
        cd sphinx-doc
        git diff --quiet || (git add build/ && git rm --cached build/doctrees/environment.pickle && git commit -a -m'[bot] update built doc' --allow-empty && git push --force --set-upstream origin pipeline)
