
name: Build docs
on:
  push:
    branches:
    - '**'        # matches every branch
    - '!gh_pages'
  schedule:
    - cron:  '*/15 * * * *'
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }} 

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses:  actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: GH_TOKEN
      if: env.GH_TOKEN == ''
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: echo "GH_TOKEN=${GITHUB_TOKEN}" >> $GITHUB_ENV        
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
        submodules: true
    # Update references
    - name: Git Repos Update
      run: | 
        chmod +x ./.github/scripts/clone.sh
        git clone https://github.com/ifm/ifm3d sphinx-doc/source/ifm3d
        cd sphinx-doc/source/ifm3d
        git checkout 3db99ea9cac13a01583aa64b2be43ad669d5af42
        cd ../../..
        git clone https://github.com/ifm/ifm3d-docs sphinx-doc/etc/ifm3d-docs
        cd sphinx-doc/etc/ifm3d-docs
        git checkout 0d978ebaed1f2e0898cff56281aad849b598c22c
        ./.github/scripts/clone.sh https://github.com/ifm/documentation main sphinx-doc/source/documentation
        ./.github/scripts/clone.sh https://github.com/ifm/ifm3d-ros.git master sphinx-doc/source/ROS/ifm3d-ros  
        ./.github/scripts/clone.sh https://github.com/ifm/ifm3d-ros2.git master sphinx-doc/source/ROS/ifm3d-ros2      
    - name: Install reqs
      run: |
        pip install -r sphinx-doc/requirements.txt
    - name: Build docs
      run: |
        cd sphinx-doc 
        rm -r -f build
        cp source/ifm3d/README.md source/ifm3d/doc/sphinx/content
        mkdir -p source/ifm3d/doc/sphinx/content/examples
        cp -r -n source/ifm3d/examples/* source/ifm3d/doc/sphinx/content/examples
        make html
        cp -r etc/ifm3d-docs/cpp_api build/html/ifm3d/doc/sphinx/
    - name: Push built docs
      run: |
        git config --global user.email "support.robotics@ifm.com"
        git config --global user.name "ifm-csr"
        git fetch -a
        git checkout main && git pull
        git checkout -B gh_pages
        git merge main
        cd sphinx-doc
        git diff --quiet || (git add build/ && git rm --cached build/doctrees/environment.pickle && git commit -a -m'[bot] update built doc' --allow-empty && git push --force --set-upstream origin gh_pages)
