
name: Build docs
on:
  push:
    branches:
    - '**'        # matches every branch
    - '!gh_pages'
  schedule:
    - cron:  '*/15 * * * *'
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }} 

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses:  actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: GH_TOKEN
      if: env.GH_TOKEN == ''
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: echo "GH_TOKEN=${GITHUB_TOKEN}" >> $GITHUB_ENV        
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
    # Update references
    - name: Git Repos Update
      run: | 
        chmod +x ./.github/scripts/clone.sh
        ./.github/scripts/clone.sh https://github.com/ifm/documentation main source/documentation
        ./.github/scripts/clone.sh https://github.com/ifm/ifm3d-ros.git master source/ROS/ifm3d-ros  
        ./.github/scripts/clone.sh https://github.com/ifm/ifm3d-ros2.git master source/ROS/ifm3d-ros2
        ./.github/scripts/clone.sh https://github.com/ifm/o3r-utilities.git main source/o3r-utilities      
    - name: Install reqs
      run: |
        pip install -r requirements.txt
    - name: Build docs
      run: |
        rm -r -f docs
        sphinx-build source docs
    # - name: Run checks
    #   run: |
    #     sphinx-build -b linkcheck source docs
    - name: Push built docs
      run: |
        git config --global user.email "support.robotics@ifm.com"
        git config --global user.name "ifm-csr"
        git fetch -a
        git checkout main && git pull
        git checkout -B gh_pages
        git merge main
        git diff --quiet || (git add build/ && git rm --cached build/doctrees/environment.pickle && git commit -a -m'[bot] update built doc' --allow-empty && git push --force --set-upstream origin gh_pages)
